# Generated by Django 4.0.4 on 2022-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='likes',
        ),
        migrations.AddField(
            model_name='vote',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
