# Generated by Django 4.0.4 on 2022-06-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='author',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='poll',
            name='bullshitter',
            field=models.CharField(max_length=75),
            preserve_default=False,
        ),
    ]
