# Generated by Django 4.0.4 on 2022-07-16 19:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_poll_dislikes_remove_poll_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='poll',
            managers=[
                ('popular_today', django.db.models.manager.Manager()),
            ],
        ),
    ]
