# Generated by Django 4.0.4 on 2022-06-28 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_category_poll_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='polls.category'),
        ),
    ]
