# Generated by Django 4.0.4 on 2022-07-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='poll',
            managers=[
            ],
        ),
    ]
