# Generated by Django 4.0.4 on 2022-06-28 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_poll_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
    ]
