# Generated by Django 4.0.4 on 2022-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_poll_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='bs_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='true_votes',
            field=models.IntegerField(default=0),
        ),
    ]
